var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/run-column/route.js")
R.c("server/chunks/[root-of-the-server]__fff0e1e4._.js")
R.c("server/chunks/_f8d3f86c._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_748cbe7d.js")
R.c("server/chunks/[root-of-the-server]__07081fb9._.js")
R.c("server/chunks/[root-of-the-server]__8893af36._.js")
R.c("server/chunks/node_modules_e0eb4235._.js")
R.c("server/chunks/node_modules_zod_v4_core_46cbde9b._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_run-column_route_actions_202e1e3b.js")
R.m(28741)
module.exports=R.m(28741).exports
