var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/chat/route.js")
R.c("server/chunks/[root-of-the-server]__b57724c4._.js")
R.c("server/chunks/_f8d3f86c._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_4d7b45bc.js")
R.c("server/chunks/[root-of-the-server]__07081fb9._.js")
R.c("server/chunks/[root-of-the-server]__8893af36._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_chat_route_actions_43cdb436.js")
R.m(18933)
module.exports=R.m(18933).exports
