var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/agent/route.js")
R.c("server/chunks/[root-of-the-server]__15f3eb25._.js")
R.c("server/chunks/_f8d3f86c._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1ba16917.js")
R.c("server/chunks/[root-of-the-server]__07081fb9._.js")
R.c("server/chunks/[root-of-the-server]__8893af36._.js")
R.c("server/chunks/node_modules_e0eb4235._.js")
R.c("server/chunks/node_modules_zod_v4_core_46cbde9b._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_agent_route_actions_590093e0.js")
R.m(42742)
module.exports=R.m(42742).exports
