var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/webhooks/polar/route.js")
R.c("server/chunks/node_modules_next_0eb9637e._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_@polar-sh_sdk_dist_esm_models_components_003372f5._.js")
R.c("server/chunks/node_modules_@polar-sh_sdk_dist_esm_models_operations_b6d6fd0e._.js")
R.c("server/chunks/node_modules_@polar-sh_sdk_dist_esm_models_errors_254d131f._.js")
R.c("server/chunks/node_modules_@polar-sh_sdk_dist_esm_funcs_02358d9f._.js")
R.c("server/chunks/node_modules_@polar-sh_sdk_dist_esm_sdk_180fd5ee._.js")
R.c("server/chunks/node_modules_@polar-sh_sdk_dist_esm_b8630f98._.js")
R.c("server/chunks/node_modules_zod_v4_c5773002._.js")
R.c("server/chunks/node_modules_convex_dist_esm_c780357f._.js")
R.c("server/chunks/node_modules_c639087c._.js")
R.c("server/chunks/[root-of-the-server]__7653c44d._.js")
R.c("server/chunks/_next-internal_server_app_api_webhooks_polar_route_actions_9daa55b4.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/webhooks/polar/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/webhooks/polar/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
