var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/templates/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2f02f868._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/_b8abe047._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2e8741b1._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_eb67f369._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__9c1adff9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_templates_page_actions_871a2c2f.js")
R.m(7229)
module.exports=R.m(7229).exports
