var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/webhooks/polar/route.js")
R.c("server/chunks/[root-of-the-server]__22f3c744._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_ee563576._.js")
R.c("server/chunks/node_modules_@polar-sh_sdk_dist_esm_index_414a4f40.js")
R.c("server/chunks/[root-of-the-server]__07081fb9._.js")
R.c("server/chunks/[root-of-the-server]__8893af36._.js")
R.c("server/chunks/node_modules_zod_v4_core_6af585dd._.js")
R.c("server/chunks/_next-internal_server_app_api_webhooks_polar_route_actions_9daa55b4.js")
R.m(11648)
module.exports=R.m(11648).exports
