var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/agent/route.js")
R.c("server/chunks/node_modules_@vercel_oidc_dist_16d0c059._.js")
R.c("server/chunks/node_modules_next_dist_2f7ed9f3._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_zod_35beed9b._.js")
R.c("server/chunks/node_modules_ai_dist_index_mjs_b0116780._.js")
R.c("server/chunks/node_modules_@ai-sdk_openai_dist_index_mjs_19cd50d6._.js")
R.c("server/chunks/node_modules_convex_dist_esm_c780357f._.js")
R.c("server/chunks/node_modules_a1aba84b._.js")
R.c("server/chunks/[root-of-the-server]__84591583._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_agent_route_actions_590093e0.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/ai/agent/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/ai/agent/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
