// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/billing" | "/contexts" | "/dashboard" | "/dashboard-admin" | "/dashboard-admin/account" | "/dashboard-admin/analytics" | "/dashboard-admin/billing" | "/dashboard/account" | "/dashboard/tables" | "/dashboard/tables/[id]" | "/login" | "/register" | "/templates" | "/templates/[id]" | "/usage"
type AppRouteHandlerRoutes = "/api/admin/billing/sync-product" | "/api/admin/users" | "/api/ai/agent" | "/api/ai/chat" | "/api/ai/context-generator" | "/api/ai/generate-template" | "/api/ai/run-column" | "/api/ai/scraper" | "/api/auth/account" | "/api/auth/account/password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/billing/checkout" | "/api/billing/confirm" | "/api/debug/env" | "/api/google-search" | "/api/health" | "/api/local-businesses" | "/api/polar/portal" | "/api/webhooks/polar"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/billing/sync-product": {}
  "/api/admin/users": {}
  "/api/ai/agent": {}
  "/api/ai/chat": {}
  "/api/ai/context-generator": {}
  "/api/ai/generate-template": {}
  "/api/ai/run-column": {}
  "/api/ai/scraper": {}
  "/api/auth/account": {}
  "/api/auth/account/password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/billing/checkout": {}
  "/api/billing/confirm": {}
  "/api/debug/env": {}
  "/api/google-search": {}
  "/api/health": {}
  "/api/local-businesses": {}
  "/api/polar/portal": {}
  "/api/webhooks/polar": {}
  "/billing": {}
  "/contexts": {}
  "/dashboard": {}
  "/dashboard-admin": {}
  "/dashboard-admin/account": {}
  "/dashboard-admin/analytics": {}
  "/dashboard-admin/billing": {}
  "/dashboard/account": {}
  "/dashboard/tables": {}
  "/dashboard/tables/[id]": { "id": string; }
  "/login": {}
  "/register": {}
  "/templates": {}
  "/templates/[id]": { "id": string; }
  "/usage": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
