var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/account/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d9da438._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/_d2ec9063._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2e8741b1._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_eb67f369._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__9c1adff9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_account_page_actions_0a55de6a.js")
R.m(62484)
module.exports=R.m(62484).exports
